---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  # Provide a list of OSes we want to use for testing.
  - DISTRIBUTION: debian8
  - DISTRIBUTION: debian9

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export CLEANUP=false

  # Download test shim.
  - wget --no-verbose --output-document=${PWD}/tests/test.sh https://gist.githubusercontent.com/Turgon37/5b6e6553ef92dc65d1c7df3e1a1e290e/raw
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - source ${PWD}/tests/test.sh

  #
  ## Specific roles tests
  #
  # Ensure APACHE2 is installed.
  - docker exec `docker_env` ${CONTAINER_ID} apache2 -v
