---

- name: "Ensure service group '{{ apache2__service_group }}' is present"
  group:
    name:   '{{ apache2__service_group }}'
    system: yes
    state:  present
  notify: [ 'restart-apache2' ]

- name: "Ensure service user '{{ apache2__service_user }}' is present"
  user:
    name:       '{{ apache2__service_user }}'
    group:      '{{ apache2__service_group }}'
    shell:      /sbin/nologin
    home:       /nonexistent
    createhome: no
    system:     yes
    state:      present
  notify: [ 'restart-apache2' ]

- name: Ensure configuration directories exists
  file:
    path:  '{{ item }}'
    owner: root
    group: '{{ apache2__service_group }}'
    mode:  0750
    state: directory
  with_items:
    - '{{ apache2__server_root }}'
    - '{{ apache2__available_modules_include_directory }}'
    - '{{ apache2__enabled_modules_include_directory }}'
    - '{{ apache2__available_sites_include_directory }}'
    - '{{ apache2__enabled_sites_include_directory }}'

- name: Ensure mutex directory exists
  file:
    path:  '{{ apache2__mutex_directory }}'
    owner: '{{ apache2__service_user }}'
    group: '{{ apache2__service_group }}'
    mode:  0755
    state: directory

- name: Ensure logging directory exists
  file:
    path:  '{{ apache2__log_directory }}'
    owner: root
    mode:  0750
    state: directory

- name: Configure listen ports
  template:
    src:   ports.conf.j2
    dest:  '{{ apache2__server_root }}/ports.conf'
    owner: root
    group: '{{ apache2__service_group }}'
    mode:  0640
  notify: [ 'restart-apache2' ]

- name: Include mods subtasks
  import_tasks: configure-mods.yml

- name: Include virtuals hosts subtasks
  import_tasks: configure-sites.yml

- name: Setup main configuration file
  template:
    src:   apache2.conf.j2
    dest:  '{{ apache2__main_configuration_file }}'
    owner: root
    group: '{{ apache2__service_group }}'
    mode:  0640
    validate: '{{ apache2__configuration_validator }}'
  notify: [ 'restart-apache2' ]
