---

- name: List available modules
  find:
    paths:     '{{ apache2__available_modules_include_directory }}'
    file_type: any
  register: _apache2__available_modules

- name: List enabled modules
  find:
    paths:     '{{ apache2__enabled_modules_include_directory }}'
    file_type: any
  register: _apache2__enabled_modules

- name: Disable all unwanted Apache modules
  file:
    state: absent
    path:  '{{ item.path }}'
  with_items: '{{ _apache2__enabled_modules.files }}'
  when: item.path|basename not in apache2__modules_enabled
  notify: [ 'restart-apache2' ]

- name: Check availability of needed Apache modules
  fail:
    msg: 'The apache module {{ item }} is not available'
  with_items: '{{ apache2__modules_enabled }}'
  when: item not in _apache2__available_modules.files|map(attribute='path')|map('basename')

- name: Enable wanted Apache modules
  file:
    src:   '{{ apache2__available_modules_include_directory }}/{{ item }}'
    dest:  '{{ apache2__enabled_modules_include_directory }}/{{ item }}'
    state: link
  with_items: '{{ apache2__modules_enabled }}'
  when: item not in _apache2__enabled_modules.files|map(attribute='path')|map('basename')
  notify: [ 'restart-apache2' ]

- name: Template modules configuration that must be override
  template:
    src:  '{{ item }}'
    dest: "{{ apache2__available_modules_include_directory }}/{{ item|basename|replace('.j2', '') }}"
  with_fileglob:
    - templates/modules.conf/*.j2
  when: item|basename|replace('.j2', '') in apache2__modules_enabled
