---

- name: List available modules
  find:
    paths: '{{ apache2__available_modules_include_directory }}'
    file_type: any
  register: _apache2__available_modules

- name: List enabled modules
  find:
    paths: '{{ apache2__enabled_modules_include_directory }}'
    file_type: any
  register: _apache2__enabled_modules

- name: Fail if an enabled module is not available
  fail:
    msg: 'The apache module {{ item }} is not available'
  with_items: '{{ apache2__modules_enabled }}'
  when: item not in
    _apache2__available_modules.files
      |map(attribute='path')|map('basename')
        |map('regex_replace', '\.load$', '')|list

- name: Disable all unwanted Apache modules
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    "{{ _apache2__enabled_modules.files|map(attribute='path')|sort|list }}"
  when: item|basename|regex_replace('\.(load|conf)$', '') not in
    apache2__modules_enabled
  notify: ['restart-apache2']

- name: Enable wanted Apache modules
  file:
    src: '{{ apache2__available_modules_include_directory }}/{{ item }}'
    dest: '{{ apache2__enabled_modules_include_directory }}/{{ item }}'
    state: link
  with_items:
    "{{ _apache2__available_modules.files
      |map(attribute='path')
        |map('basename')
          |select('match',
                  '^('~apache2__modules_enabled|join('|')~')\\.(conf|load)')
            |sort
              |list }}"
  when: item|regex_replace('(\.load|\.conf)$', '') in apache2__modules_enabled
    and item not in _apache2__enabled_modules.files
                      |map(attribute='path')
                        |map('basename')
                          |list
  notify: ['restart-apache2']

- name: Template modules configuration that must be override
  template:
    src: '{{ item }}'
    dest: "{{ apache2__available_modules_include_directory }}/\
      {{ item|basename|replace('.j2', '') }}"
  with_fileglob:
    - templates/modules.conf/*.j2
  when: item|basename|replace('.conf.j2', '') in apache2__modules_enabled|list
