---

- name: Create custom fact directory
  file:
    path: "{{ facts__dir|d('/etc/ansible/facts.d') }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: ['apache2', 'apache2-facts']

- name: Insert custom fact file
  copy:
    src: files/apache2.facts.py
    dest: "{{ facts__dir|d('/etc/ansible/facts.d') }}/apache2.fact"
    mode: 0755
  tags: ['apache2', 'apache2-facts']
