---
# tasks file for apache2

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- import_tasks: init.yml
  tags: ['always']

- import_tasks: install.yml
  tags: ['apache2', 'apache2-install']

- import_tasks: configure.yml
  tags: ['apache2', 'apache2-configure']

- import_tasks: service.yml
  tags: ['apache2', 'apache2-service']

- include_tasks: facts.yml
  when: apache2__facts|bool
  tags: ['apache2', 'apache2-facts']
