---
# tasks file for apache2

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Import init tasks
  import_tasks: init.yml
  tags: ['always']

- name: Import install tasks
  import_tasks: install.yml
  tags: ['apache2', 'apache2-install']

- name: Import configure tasks
  import_tasks: configure.yml
  tags: ['apache2', 'apache2-configure']

- name: Import service tasks
  import_tasks: service.yml
  tags: ['apache2', 'apache2-service']

- name: Optionally import monitoring tasks
  include_tasks: 'monitoring/{{ apache2__monitoring }}.yml'
  when: apache2__monitoring is defined
  tags: ['apache2', 'apache2-monitoring']

- name: Optionally include facts tasks
  include_tasks: facts.yml
  when: apache2__facts|bool
  tags: ['apache2', 'apache2-facts']
