---
- name: List available mods
  find:
    paths: "{{ apache2__server_root }}/mods-available/"
  register: available_mods
  tags: ['apache2']

- name: List enabled mods
  find:
    paths: "{{ apache2__server_root }}/mods-enabled/"
  register: enabled_mods
  tags: ['apache2']

- name: Disable all unwanted Apache mods
  become: yes
  file:
    state: absent
    path: '{{ item.path }}'
  with_items: "{{ enabled_mods.files }}"
  when: item.path | basename not in apache2__mods_enabled
  notify: [ 'test apache configuration and restart' ]
  tags: ['apache2']

- name: Check availability of needed Apache mods.
  fail:
    msg: "The apache module {{ item }} is not available"
  with_items: "{{ apache2__mods_enabled }}"
  when: item not in available_mods.files|map(attribute='path')|map('basename')

- name: Enable selected Apache mods.
  become: yes
  file:
    src: "{{ apache2__server_root }}/mods-available/{{ item }}"
    dest: "{{ apache2__server_root }}/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache2__mods_enabled }}"
  when: item not in enabled_mods.files|map(attribute='path')|map('basename')
  notify: [ 'test apache configuration and restart' ]
  tags: ['apache2']
