---
- name: List available sites
  find:
    paths: "{{ apache2__server_root }}/sites-available/"
  register: available_sites
  tags: ['apache2']

- name: List enabled sites
  find:
    paths: "{{ apache2__server_root }}/sites-enabled/"
    file_type: link
  register: enabled_sites
  tags: ['apache2']

- name: Remove unknown availables sites
  become: yes
  file:
    state: absent
    path: '{{ item.path }}'
  with_items: "{{ available_sites.files }}"
  when: item.path | basename | replace('.conf', '') not in apache2__virtual_hosts.keys()
  notify: [ 'test apache configuration and restart' ]
  tags: ['apache2']

- name: Setup availables sites
  become: yes
  template:
    src: 'vhost.conf.j2'
    dest: "{{ apache2__server_root }}/sites-available/{{ item.key|replace(' ', '_') }}.conf"
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_dict: '{{ apache2__virtual_hosts }}'
  notify: [ 'test apache configuration and restart' ]
  tags: ['apache2']

- name: Disable all unwanted Apache sites
  become: yes
  file:
    state: absent
    path: '{{ item.path }}'
  with_items: "{{ enabled_sites.files }}"
  when: item.path | basename | replace('.conf', '') not in apache2__virtual_hosts.keys()
  notify: [ 'test apache configuration and restart' ]
  tags: ['apache2']

- name: Enable wanted Apache sites.
  become: yes
  file:
    src: "{{ apache2__server_root }}/sites-available/{{ item|replace(' ', '_') }}.conf"
    dest: "{{ apache2__server_root }}/sites-enabled/{{ item|replace(' ', '_') }}.conf"
    state: link
  with_items: '{{ apache2__virtual_hosts.keys() }}'
  when: apache2__virtual_hosts[item].enabled | d(True) | bool
  notify: [ 'test apache configuration and restart' ]
  tags: ['apache2']
